### ISSUE TITLE
Max level filter for Coffin Regex

### ISSUE THREAD

**Issue by Rave96** [ugimser/ugimser.github.io#2]
Hey there!
First of all: big thanks for your page! Incredible useful tool for sorting out the stash! :D 

Now to my question: Would it be possible to add a max level filter to the coffin regex? (maybe even a range, since the min level one is already there)
My problem with it is, that im farming t16, so my max coffins are lv 83 and when i filter for the more expensive corpses, all my corpses that are lower than 84 also show up.

**Comment by ugimser** [comment]
Done
